version: '3'
services:

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_USER: gabriel360
      MYSQL_PASSWORD: gabriel360
      MYSQL_DATABASE: db_doterra
      MYSQL_ALLOW_EMPTY_PASSWORD: true

    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"